# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-env-var',
                'doc_host': 'https://tylere.github.io',
                'git_url': 'https://github.com/tylere/test-env-var',
                'lib_path': 'test_env_var'},
  'syms': {'test_env_var.core': {'test_env_var.core.foo': ('core.html#foo', 'test_env_var/core.py')}}}